version: '3.3'

services:
  client:
    container_name: undrr-mangrove-client-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6006:6006
    image: undrr-mangrove-client
    volumes:
      # `application` should be the same as `WORKSPACE_DIR` in `Dockerfile`
      - .:/data/storybook
    command: ['tail', '-f', '/dev/null']
