#!/usr/bin/env node

/**
 * icon-build.cjs
 *
 * Reads SVG files listed in icon-map.cjs, optimises them with SVGO,
 * URL-encodes them, and writes SCSS mask-image rules to
 * stories/Atom/Icons/_icon-definitions.scss.
 *
 * The generated file is imported by stories/Atom/Icons/icons.scss.
 *
 * Part of the icon font → CSS mask-image migration.
 * See: https://github.com/unisdr/undrr-mangrove/issues/906
 *
 * Usage:  node scripts/icon-build.cjs
 */

const fs = require('fs');
const path = require('path');
const { optimize } = require('svgo');
const iconMap = require('./icon-map.cjs');

const OUTPUT = path.resolve(__dirname, '../stories/Atom/Icons/_icon-definitions.scss');

// SVGO config: strip metadata, remove dimensions (we size via CSS),
// keep viewBox, inline styles → attributes for cleaner output.
// SVGs must have a viewBox for mask-size: contain to work correctly.
const svgoConfig = {
  plugins: [
    'preset-default',
    'removeDimensions',
    'sortAttrs',
    { name: 'removeAttrs', params: { attrs: ['class'] } },
  ],
};

function encodeSvg(svgString) {
  // Minimal URI encoding that keeps the data URI readable and compact.
  // Encodes only the characters that break url() in CSS.
  // Note: double quotes are replaced with single quotes because the
  // outer CSS delimiter is url("..."). SVG attributes accept either style.
  return svgString
    .replace(/\n/g, '')
    .replace(/\r/g, '')
    .replace(/\t/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim()
    .replace(/#/g, '%23')
    .replace(/"/g, "'");
}

function buildIconDefinitions() {
  const names = Object.keys(iconMap);
  const errors = [];

  // Validate all SVG paths exist before doing any work.
  for (const name of names) {
    const svgPath = path.resolve(iconMap[name]);
    if (!fs.existsSync(svgPath)) {
      errors.push(`  mg-icon-${name}: ${iconMap[name]} not found`);
    }
  }

  if (errors.length > 0) {
    console.error('build-icons: missing SVG files:\n' + errors.join('\n'));
    process.exit(1);
  }

  const rules = [];
  const warnings = [];

  for (const name of names) {
    const svgPath = path.resolve(iconMap[name]);
    const raw = fs.readFileSync(svgPath, 'utf8');
    const optimised = optimize(raw, { ...svgoConfig, path: svgPath });
    const encoded = encodeSvg(optimised.data);
    const dataUri = `url("data:image/svg+xml,${encoded}")`;

    // Warn if viewBox is missing — icon won't scale correctly via mask-size: contain.
    if (!optimised.data.includes('viewBox')) {
      warnings.push(`  mg-icon-${name}: missing viewBox (icon may not scale correctly)`);
    }

    rules.push(
      `.mg-icon-${name}::before {\n` +
      `  --mg-icon-svg: ${dataUri};\n` +
      `}`
    );
  }

  if (warnings.length > 0) {
    console.warn('build-icons: warnings:\n' + warnings.join('\n'));
  }

  const header =
    '// Auto-generated by scripts/icon-build.cjs — do not edit by hand.\n' +
    '// To regenerate: yarn build:icons\n' +
    `// ${names.length} icons from Lucide, OCHA, and custom SVG sources.\n`;

  const output = header + '\n' + rules.join('\n\n') + '\n';

  // Skip write if content is unchanged (avoids triggering file watchers).
  const existing = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
  if (existing === output) {
    console.log(`build-icons: ${names.length} icons, no changes`);
    return;
  }

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, output, 'utf8');

  console.log(`build-icons: wrote ${names.length} icon rules to ${path.relative(process.cwd(), OUTPUT)}`);
}

buildIconDefinitions();
