name: Build and Push dist to dist branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-push-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set Yarn Version
        run: yarn set version berry

      - name: Install dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install --refresh-lockfile

      - name: Build project
        run: yarn run build

      - name: Push dist to dist branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create a temporary directory for the dist branch
          mkdir -p /tmp/dist-branch
          cp -r dist/* /tmp/dist-branch/

          # Check if dist branch exists
          if git ls-remote --heads origin dist | grep -q dist; then
            git fetch origin dist
            git checkout dist
          else
            git checkout --orphan dist
          fi

          # Remove all files from the working directory
          rm -rf .* * 2>/dev/null || true

          # Copy dist files
          cp -r /tmp/dist-branch/* .

          # Add and commit
          git add .
          git commit -m "Deploy dist from ${{ github.sha }}"
          git push --force origin dist