name: Publish to NPM Registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to publish (e.g., v1.0.0)'
        required: true
        type: string
      registry:
        description: 'NPM registry to publish to'
        required: true
        type: choice
        options:
          - 'npm'
          - 'github'
        default: 'github'

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Setup Node.js for npm registry
        if: ${{ inputs.registry == 'npm' }}
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Node.js for GitHub registry
        if: ${{ inputs.registry == 'github' }}
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@unisdr'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      # Prepare package for publishing - only include dist files
      - name: Prepare package files
        run: |
          mkdir -p npm-package/dist
          cp -r dist/* npm-package/dist/
          cp package.json npm-package/
          cp README.md npm-package/
          cp LICENSE npm-package/ || echo "No LICENSE file found"

          # Create a custom package.json for publishing
          node -e '
            const pkg = require("./package.json");
            const registry = "${{ inputs.registry }}";
            // Keep only essential fields
            const newPkg = {
              name: pkg.name,
              version: pkg.version,
              description: pkg.description,
              main: "dist/index.js",
              files: ["dist/**/*"],
              repository: pkg.repository,
              keywords: pkg.keywords,
              author: pkg.author,
              license: pkg.license
            };
            
            // Add registry-specific config
            if (registry === "github") {
              newPkg.publishConfig = {
                registry: "https://npm.pkg.github.com",
                access: "public"
              };
            }
            
            require("fs").writeFileSync("npm-package/package.json", JSON.stringify(newPkg, null, 2));
          '

      - name: Publish to npm registry
        if: ${{ inputs.registry == 'npm' }}
        working-directory: npm-package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        if: ${{ inputs.registry == 'github' }}
        working-directory: npm-package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
